language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
sudo: false

before_install:
  - npm install eslint babel-eslint eslint-plugin-react babel-cli \
                babel-plugin-transform-object-rest-spread \
                babel-preset-env babel-preset-stage-0 \
                eslint-config-google
  - npm run lint
  - git submodule update --init --recursive

script:
  - npm run build

after_script:
  - npm run test
